USE apostols_UEAS;

CREATE TABLE IF NOT EXISTS PERSONAS(
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
NOMBRES VARCHAR (150) NOT NULL,
APELLIDOS VARCHAR (150) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
TELEFONO VARCHAR (10) ,
CELULAR VARCHAR (10) NOT NULL,
CORREO VARCHAR (150) NOT NULL,
DIRECCION VARCHAR (200) NOT NULL,
FOTO VARCHAR (30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (CEDULA)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CURSOS (
ID INT AUTO_INCREMENT NOT NULL,
COD_CURSO VARCHAR (10) NOT NULL,
NOMBRE_CURSO VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_CURSO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PARALELOS(
ID INT AUTO_INCREMENT NOT NULL,
COD_PARALELO VARCHAR (1) NOT NULL,
NOMBRE_PARALELO VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_PARALELO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS JORNADAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
NOMBRE_JORNADA VARCHAR (50) NOT NULL,
PRIMARY KEY (ID)
)ENGINE = InnoDB;
ALTER TABLE JORNADAS ADD UNIQUE (COD_JORNADA);

CREATE TABLE IF NOT EXISTS LECTIVO (
ID INT AUTO_INCREMENT NOT NULL,
COD_LECTIVO VARCHAR (15) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_LECTIVO)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS ALUMNOS(
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
ENFERMEDAD TEXT,
ALERGIAS TEXT,
CEDULA_REPRESENTANTE VARCHAR (13),
PRIMARY KEY (ID),
UNIQUE (CEDULA),
CONSTRAINT ALUMNOS_PERSONAS FOREIGN KEY (CEDULA) REFERENCES apostols_UEAS.PERSONAS (CEDULA),
CONSTRAINT ALUMNOS_R_PERSONAS FOREIGN KEY (CEDULA_REPRESENTANTE) REFERENCES apostols_UEAS.PERSONAS (CEDULA)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS DOCENTES (
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (CEDULA),
CONSTRAINT DOCENTES_PERSONAS FOREIGN KEY (CEDULA) REFERENCES apostols_UEAS.PERSONAS (CEDULA)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS COD_AULAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_AULA VARCHAR (10) NOT NULL,
NOMBRE_AULA VARCHAR (50) NOT NULL,
COD_CURSO VARCHAR (10) NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_AULA),
CONSTRAINT COD_AULAS_CURSOS FOREIGN KEY (COD_CURSO) REFERENCES CURSOS (COD_CURSO),
CONSTRAINT COD_AULAS_PARALELO FOREIGN KEY (COD_PARALELO) REFERENCES PARALELOS (COD_PARALELO)
)ENGINE = InnoDB;

ALTER TABLE COD_AULAS ADD COLUMN COD_JORNADA VARCHAR (10) NOT NULL;
ALTER TABLE COD_AULAS ADD CONSTRAINT JORNADA_COD_AULAS FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA);

CREATE TABLE IF NOT EXISTS AULAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_AULA VARCHAR (10) NOT NULL,
CEDULA_ALUMNO VARCHAR (10) NOT NULL,
CEDULA_DOCENTE VARCHAR (10) NOT NULL,
COD_LECTIVO VARCHAR (15) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT AULAS_ALUMNOS FOREIGN KEY (CEDULA_ALUMNO) REFERENCES ALUMNOS (CEDULA),
CONSTRAINT AULAS_DOCENTES FOREIGN KEY (CEDULA_DOCENTE) REFERENCES DOCENTES (CEDULA),
CONSTRAINT AULAS_LECTIVO FOREIGN KEY (COD_LECTIVO) REFERENCES LECTIVO (COD_LECTIVO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS USUARIOS (
ID INT AUTO_INCREMENT NOT NULL,
USER VARCHAR (13) NOT NULL,
PASSWORD VARCHAR (100) NOT NULL,
TYPE INT NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT USUARIOS_PERSONAS FOREIGN KEY (USER) REFERENCES PERSONAS (CEDULA)
)ENGINE = InnoDB;

CREATE TABLE ASISTENCIAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_AULA VARCHAR (10) NOT NULL,
CEDULA_ALUMNO  VARCHAR (13) NOT NULL,
FECHA_ASISTENCIA DATE NOT NULL,
ESTADO_ASISTENCIA VARCHAR (2) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT ASISTENCIAS_AULAS FOREIGN KEY (CEDULA_ALUMNO) REFERENCES AULAS (CEDULA_ALUMNO)
)ENGINE = InnoDB;

CREATE TABLE JUSTIFICACIONES_FALTAS (
ID INT AUTO_INCREMENT NOT NULL,
CEDULA_ALUMNO VARCHAR (13) NOT NULL,
MOTIVO TEXT NOT NULL,
FECHA_ASISTENCIA DATE NOT NULL,
DOC_RESPALDO VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT JUSTIFICACIONES_ASISTENCIAS FOREIGN KEY (CEDULA_ALUMNO) REFERENCES ASISTENCIAS (CEDULA_ALUMNO)
)ENGINE = InnoDB;

ALTER TABLE AULAS ADD CONSTRAINT AULAS_COD_AULAS FOREIGN KEY (COD_AULA) REFERENCES COD_AULAS (COD_AULA);