-- CREATE DATABASE UE_ApostolSantiago;
USE apostols_UEAS;

CREATE TABLE IF NOT EXISTS PERSONAS(
ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR (13) NOT NULL,
NOMBRES VARCHAR (50) NOT NULL,
APELLIDOS VARCHAR (50) NOT NULL,
FECHA DATE NOT NULL,
DIRECCION VARCHAR (200) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
CORREO VARCHAR (200) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (CEDULA),
UNIQUE (CORREO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS REPRESENTANTES (
ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR (13) NOT NULL,
CEDULA_ALUMNO VARCHAR (13) NOT NULL,
IMAGEN_REPRESENTANTE VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT REPRESENTANTE_CEDULA FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT REPRESENTANTE_ALUMNO FOREIGN KEY (CEDULA_ALUMNO) REFERENCES PERSONAS (CEDULA)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_PADRES(
ID INT NOT NULL AUTO_INCREMENT,
TIPO_PADRE INT (1) NOT NULL,
NAME_TIPO VARCHAR (20) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (TIPO_PADRE)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PADRES (
ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR (13) NOT NULL,
CEDULA_ALUMNO VARCHAR (13) NOT NULL,
TIPO_PADRE INT (1) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT PADRE_CEDULA FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT PADRE_ALUMNO FOREIGN KEY (CEDULA_ALUMNO) REFERENCES PERSONAS (CEDULA),
CONSTRAINT PARE_TIPO FOREIGN KEY (TIPO_PADRE) REFERENCES TIPO_PADRES (TIPO_PADRE)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID INT AUTO_INCREMENT NOT NULL,
CORREO VARCHAR (200) NOT NULL,
PASSWORD VARCHAR (200) NOT NULL,
PRIMARY KEY (ID),
INDEX (CORREO),
CONSTRAINT USUARIOS FOREIGN KEY (CORREO) REFERENCES PERSONAS (CORREO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS NIVELES (
ID INT NOT NULL AUTO_INCREMENT,
COD_NIVEL VARCHAR (10) NOT NULL,
NAME_NIVEL VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_NIVEL)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PARALELOS(
ID INT NOT NULL AUTO_INCREMENT,
COD_PARALELO VARCHAR (10) NOT NULL,
NAME_PARALELO VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_PARALELO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS JORNADAS (
ID INT NOT NULL AUTO_INCREMENT,
COD_JORNADA VARCHAR (10) NOT NULL,
NAME_JORNADA VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_JORNADA)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANIO_LECTIVO (
ID INT NOT NULL AUTO_INCREMENT,
COD_LECTIVO VARCHAR (10),
PRIMARY KEY (ID),
UNIQUE (COD_LECTIVO)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ALUMNOS (
ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR (13) NOT NULL,
COD_NIVEL VARCHAR (10) NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
COD_LECTIVO VARCHAR (10) NOT NULL,
ENFERMEDAD TEXT NOT NULL,
ALERGIA TEXT NOT NULL,
IMAGEN_ALUMNO VARCHAR (50) NOT NULL,
IMAGEN_PERSONA_AUTORIZADA VARCHAR (50) NOT NULL,
IAMGEN_CROQUIS VARCHAR (50) NOT NULL,
PRIMARY KEY (ID),
INDEX (CEDULA),
CONSTRAINT ALUMNOS_CEDULA FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT ALUMNOS_NIVEL FOREIGN KEY (COD_NIVEL) REFERENCES NIVELES (COD_NIVEL),
CONSTRAINT ALUMNOS_PARALELO FOREIGN KEY (COD_PARALELO) REFERENCES PARALELOS (COD_PARALELO),
CONSTRAINT ALUMNOS_JORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA),
CONSTRAINT ALUMNOS_LECTIVO FOREIGN KEY (COD_LECTIVO) REFERENCES ANIO_LECTIVO (COD_LECTIVO)
)ENGINE = InnoDB;

CREATE TABLE CATEDRAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_CATEDRA VARCHAR (10) NOT NULL,
NOMBRE_CATEDRA VARCHAR (100) NOT NULL,
PRIMARY KEY (ID),
INDEX (COD_CATEDRA)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DOCENTES (
ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR (13) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
PRIMARY KEY (ID),
INDEX (CEDULA),
CONSTRAINT DOCENTE_CEDULA FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT DOCENTE_JORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA)
)ENGINE = InnoDB; 

-- CREATE TABLE IF NOT EXISTS CATEDRAS (
-- ID INT NOT NULL AUTO_INCREMENT,
-- COD_CATEDRA VARCHAR(10) NOT NULL,
-- NAME_CATEDRA VARCHAR (50) NOT NULL,
-- COD_NIVEL VARCHAR (10) NOT NULL,
-- COD_LECTIVO VARCHAR (10) NOT NULL,
-- COD_JORNADA VARCHAR (10) NOT NULL,
-- PRIMARY KEY (ID),
-- UNIQUE (COD_CATEDRA),
-- CONSTRAINT CATEDRA_NIVEL FOREIGN KEY (COD_NIVEL) REFERENCES NIVELES (COD_NIVEL),
-- CONSTRAINT CATEDRA_JORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA),
-- CONSTRAINT CATEDRA_LECTIVO FOREIGN KEY (COD_LECTIVO) REFERENCES ANIO_LECTIVO (COD_LECTIVO)
-- ) ENGINE = InnoDB;

CREATE TABLE ASISTENCIAS (
ID INT NOT NULL AUTO_INCREMENT,
CEDULA_ALUMNO VARCHAR (13) NOT NULL,
FECHA DATE NOT NULL,
ESTADO INT (1) NOT NULL,
COD_LECTIVO VARCHAR (10) NOT NULL,
COD_CATEDRA VARCHAR (10) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT AISTENCIAS_ALUMNOS FOREIGN KEY (CEDULA_ALUMNO) REFERENCES ALUMNOS (CEDULA),
CONSTRAINT AISTENCIAS_CATEDRA FOREIGN KEY (COD_CATEDRA) REFERENCES CATEDRAS (COD_CATEDRA)
)ENGINE = InnoDB;

CREATE TABLE CURSOS(
ID INT AUTO_INCREMENT NOT NULL,
COD_CURSO VARCHAR (10) NOT NULL,
COD_LECTIVO VARCHAR (10) NOT NULL,
COD_NIVEL VARCHAR (10) NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
CEDULA_DOCENTE VARCHAR (13) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT CURSOS_LECTIVO FOREIGN KEY (COD_LECTIVO) REFERENCES ANIO_LECTIVO (COD_LECTIVO),
CONSTRAINT CURSOS_NIVEL FOREIGN KEY (COD_NIVEL) REFERENCES NIVELES (COD_NIVEL),
CONSTRAINT CURSOS_PARALELO FOREIGN KEY (COD_PARALELO) REFERENCES PARALELOS (COD_PARALELO),
CONSTRAINT CURSOS_JORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA),
CONSTRAINT CURSOS_CEDULAD FOREIGN KEY (CEDULA_DOCENTE) REFERENCES DOCENTES (CEDULA)
)ENGINE = InnoDB;

